### PR TITLE
Convert to WebExtensions

### LINKED ISSUE #7: Convert to WebExtensions
Firefox is [deprecating the old extensions](https://support.mozilla.org/en-US/kb/firefox-add-technology-modernizing) and will only support WebExtensions in the near future. This plugin doesn't deal with any Firefox internals, it's all JavaScript, so I don't think it's going to be a lot of work.

### PR DESCRIPTION
**Pull request by jomo**
Fixes #7. Also changed:

- Removed junk from the repo
- Added SVG icon
- Switched to ES6
- Updated .eslintrc
- Added Google Chrome Support
- Fixed selected text detection
- Slight code improvements on a few occasions
- Removed all unnecessary code
- Bumped version number
- Updated changelog

Sorry it's one single commit, but I was pretty much touching every file already.

### CODE REVIEW

**Comment by jomo** [comment]
@brettz9 any chance this will be merged?

**Comment by brettz9** [comment]
My apologies, I hadn't been getting email notifications, so I unfortunately missed your info here.

I intend to take a look when I have a little time, hopefully within the next week or so. Let me know if you have any other changes coming through the pipeline...

**Comment by brettz9** [comment]
This is looking very good--I have a couple questions...

1. Are there any browsers you know of supporting WebExtensions and the non-standard `document.caretRangeFromPoint` but aren't supporting the standard `document.caretPositionFromPoint`?
1. By "Fixed selected text detection", are you referring to avoiding the Caret selection? Otherwise, I didn't see any fixes per se, except for some useful optimizations.

Also, IIRC, the reason I had two context menu entries before was because I found a good number of times that I had forgotten that I had some text highlighted on a page and I would then inadvertently give myself the anchor relative to that point. I might try it again this way with just one selection and see whether I feel I need to add back the extra menu item or not.

And I seem to remember having tried the "contextmenu" event over the "click" event myself, but maybe it just wasn't working for the Addons SDK and now it is ok with WebExtensions...

**Comment by brettz9** [comment]
I've made a number of changes, mostly smaller ones, though more significantly I switched our using the heavier `content_script` privileges to the lesser `activeTab` privilege, and then (also adding the webextension-polyfill), conditionally injecting via `executeScript`. It turns out we also don't need the `tabs` privilege, as that is only needed for privileged portions of that API (which we don't need).

Would you take a look at my "webext" branch and see if that works for you so I can release?

**Comment by brettz9** [comment]
@jomo : Please let me know if you intend to review and confirm it's working for you, as I may go ahead with a release if I don't hear back.

**Comment by jomo** [comment]
Sorry for the late reply.

> browsers supporting `document.caretRangeFromPoint` but not `document.caretPositionFromPoint`?

Good point. Theoretically Google Chrome 43 - 52, guess we can ignore that.  
Also, it looks like Firefox has completely dropped support for this.

> "Fixed selected text detection"

I probably meant that selection is only used when there is an actual selection _range_, not just a selection caused by clicking on the page.

---

The changes in the webext branch look fine to me, I've tested the plugin and it seems to be working as it should.

**Comment by brettz9** [comment]
@jomo : I've unfortunately realized that my solution with `activeTab` privileges is inadequate. I've filed https://bugzilla.mozilla.org/show_bug.cgi?id=1437497 so that I can use it. I may see about reverting this functionality to use a content script for the time being. :-(

**Comment by rugk** [comment]
Great work, here! So does it work with Firefox 58 (even without that last bug you've filled)? So can we expect a release (on AMO), soon?

**Comment by brettz9** [comment]
Yes, it's working with Firefox 58 and available now on https://addons.mozilla.org/en-US/firefox/addon/jump-to-anchor/ .

I'm currently trying to tweak it to work fully in Chrome, as Chrome is having a problem with the SVG icon. When I may get it working, I intend to post back here for any interested.

But it's all good now for Firefox, though with the unfortunate requirement that you have to agree to content script privileges and have the code injected into every page rather than only when you use it.

**Comment by rugk** [comment]
It works, great!

**Comment by brettz9** [comment]
Available for Chrome now as well at https://chrome.google.com/webstore/detail/jump-to-anchor/fhbjjkmbahpmoegppmljagmakkeomlmb

**Comment by brettz9** [comment]
And very many thanks to @jomo for doing all the work of migrating into the new format! If the manifest starts accepting multiple authors, I'll gladly add you there...

Btw, it turns out `document.caretRangeFromPoint` was needed after all--it appears MDN might be wrong about Chrome support as `document.caretPositionFromPoint` turns up `undefined` and there's an open issue for it: https://bugs.chromium.org/p/chromium/issues/detail?id=388976

**Comment by brettz9** [comment]
Btw, I've just published an update (approved on AMO and at the Chrome Web Store) which avoids adding, regardless of user setting, the selection context menu if no selection has been made. Because this feature is now available, I've changed the default for the option to be true, but people can still opt back to having only a single menu item regardless. I think this way is better for discoverability (~~~even if it is mildly annoying as a default on Chrome since Chrome always ends up with a selection~~~).

**Comment by brettz9** [comment]
Actually, I pushed a fix and improvement to the update I had mentioned a few hours ago (also available on both stores already) which makes the default on Chrome (and any other browsers besides Firefox) different from Firefox. So I think things are now where they should be.

**Comment by rugk** [comment]
Thanks, that looks quite good. However, is it possible to not put that into a submenu? So I have these two items directly without looking into the submenu?

**Pull request merged**
